spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Ai
    username: root
    password: bpea2641
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect  # MariaDB Dialect ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
